---
- name: Install docker
  yum: name=docker-io state=present

- name: Start docker
  service: name=docker state=started

- name: Check if cadvisor is started
  shell: docker inspect cadvisor &>/dev/null
  ignore_errors: True
  changed_when: False
  register: docker_inspect_cadvisor

- name: Start cadvisor container
  command:
    docker run -d --name=cadvisor
    -p 8080:8080
    -v /:/rootfs:ro
    -v /var/run:/var/run:rw
    -v /sys:/sys:ro
    -v /var/lib/docker/:/var/lib/docker:ro
    google/cadvisor
  when: docker_inspect_cadvisor|failed
