---
- name: Install docker
  yum: name=docker-io state=present

- name: Start docker
  service: name=docker state=started

- name: Check if etcd is started
  shell: docker inspect etcd &>/dev/null
  ignore_errors: True
  changed_when: False
  register: docker_inspect_etcd

- name: Start etcd container
  command: docker run -d --name etcd -p 4001:4001 coreos/etcd
  when: docker_inspect_etcd|failed
